import {test} from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
test('RLS: público lê, só administrador edita; validação e versão são obrigatórias',async()=>{
 const db=new PGlite();
 await db.exec(`create role anon; create role authenticated; create schema auth; create schema storage;
 create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid,bucket_id text,name text);alter table storage.objects enable row level security;
 create function storage.foldername(name text) returns text[] language sql immutable as $$select string_to_array(name,'/')$$;
 grant usage on schema public,auth,storage to anon,authenticated;grant insert,select on storage.objects to authenticated;
 insert into auth.users values('11111111-1111-4111-8111-111111111111'),('22222222-2222-4222-8222-222222222222');`);
 await db.exec(readFileSync('supabase/schema.sql','utf8'));await db.exec(readFileSync('supabase/seed.sql','utf8'));
 await db.exec(`insert into public.wr_admins values('11111111-1111-4111-8111-111111111111');set role anon;`);
 assert.equal((await db.query('select * from public.wr_champion_catalog')).rows.length,141);
 await assert.rejects(db.exec(`insert into public.wr_champion_overrides(champion_id,rotas) values('aatrox',array['TOP']);`));
 await db.exec(`reset role;set role authenticated;set request.jwt.claim.sub='22222222-2222-4222-8222-222222222222';`);
 await assert.rejects(db.exec(`insert into public.wr_champion_overrides(champion_id,rotas) values('aatrox',array['TOP']);`));
 await assert.rejects(db.exec(`insert into public.wr_admins values('22222222-2222-4222-8222-222222222222');`));
 await assert.rejects(db.exec(`insert into storage.objects(bucket_id,name) values('wr-champion-images','aatrox/11111111-1111-4111-8111-111111111111.webp');`));
 await db.exec(`set request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';`);
 await db.exec(`insert into public.wr_champion_overrides(champion_id,rotas) values('aatrox',array['MID','SUPPORT']);`);
 assert.equal((await db.query('select version from public.wr_champion_overrides')).rows[0].version,1);
 await db.exec(`update public.wr_champion_overrides set rotas=array['JUNGLE'] where champion_id='aatrox' and version=1;`);
 assert.equal((await db.query('select version from public.wr_champion_overrides')).rows[0].version,2);
 assert.equal((await db.query(`update public.wr_champion_overrides set rotas=array['TOP'] where champion_id='aatrox' and version=1 returning *`)).rows.length,0);
 for(const routes of [`array[]::text[]`,`array['TOP','TOP']`,`array['INVALID']`,`array[null]::text[]`])await assert.rejects(db.exec(`update public.wr_champion_overrides set rotas=${routes} where champion_id='aatrox';`));
 await assert.rejects(db.exec(`update public.wr_champion_overrides set version=10 where champion_id='aatrox';`));
 await assert.rejects(db.exec(`insert into public.wr_champion_overrides(champion_id,rotas) values('inventado',array['TOP']);`));
 await db.exec(`insert into storage.objects(bucket_id,name) values('wr-champion-images','aatrox/11111111-1111-4111-8111-111111111111.webp');`);
 await assert.rejects(db.exec(`insert into storage.objects(bucket_id,name) values('other','aatrox/11111111-1111-4111-8111-111111111111.webp');`));
 await db.exec(`set request.jwt.claim.sub='22222222-2222-4222-8222-222222222222';`);
 assert.equal((await db.query(`update public.wr_champion_overrides set rotas=array['TOP'] where champion_id='aatrox' returning *`)).rows.length,0);
 await db.exec('reset role;set role anon;');assert.equal((await db.query('select rotas from public.wr_champion_overrides')).rows[0].rotas[0],'JUNGLE');
 await db.close();
});
